version: "3.4"
services:
  app:
    image: couchdb-backend:latest
    restart: unless-stopped
    networks:
      - traefik_public
      - couch_public
    labels:
      - "traefik.http.routers.couchdbbackend.rule=Host(`api.davlin.io`) && Method(`GET`, `POST`) && PathPrefix(`/v1/couch`)"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.services.couchdbbackend.loadbalancer.server.port=80"
      - "traefik.http.routers.couchdbbackend.entrypoints=https"
      - "traefik.http.routers.couchdbbackend.tls=true"

networks:
  traefik_public:
    external: true
  couch_public:
    external: true
