export const employeeInput = [
  {
    lastName: "Anderson",
    firstName: "Susan",
    middleInitial: "L",
    street: "108th",
    city: "Omaha",
    gender: "F",
  },
  {
    lastName: "Brady",
    firstName: "Dan",
    middleInitial: "L",
    street: "P street",
    city: "Lincoln",
    gender: "M",
  },
  {
    lastName: "Chen",
    firstName: "Peter",
    middleInitial: "K",
    street: "124th",
    city: "Omaha",
    gender: "M",
  },
  {
    lastName: "Clemson",
    firstName: "Ann",
    middleInitial: "M",
    street: "O",
    city: "Lincoln",
    gender: "F",
  },
  {
    lastName: "Dale",
    firstName: "Mary",
    middleInitial: "K",
    street: "132th",
    city: "Omaha",
    gender: "F",
  },
  {
    lastName: "Gill",
    firstName: "Mary",
    middleInitial: "L",
    street: "P street",
    city: "Lincoln",
    gender: "F",
  },
  {
    lastName: "Harrison",
    firstName: "Susan",
    middleInitial: "M",
    street: "Old Mill",
    city: "Omaha",
    gender: "F",
  },
  {
    lastName: "Jackson",
    firstName: "Kim",
    middleInitial: "A",
    street: "178th",
    city: "Omaha",
    gender: "F",
  },
  {
    lastName: "Jason",
    firstName: "Pat",
    middleInitial: "M",
    street: "8th",
    city: "C.Bluffs",
    gender: "M",
  },
  {
    lastName: "Kumar",
    firstName: "Paul",
    middleInitial: "T",
    street: "Dodge",
    city: "Omaha",
    gender: "M",
  },
  {
    lastName: "Orr",
    firstName: "Susanne",
    middleInitial: "S",
    street: "Q",
    city: "Omaha",
    gender: "F",
  },
  {
    lastName: "Peterson",
    firstName: "Mike",
    middleInitial: "E",
    street: "Blondo",
    city: "Omaha",
    gender: "M",
  },
  {
    lastName: "Powell",
    firstName: "Tom",
    middleInitial: "E",
    street: "Broadway",
    city: "C.Bluffs",
    gender: "M",
  },
  {
    lastName: "Quinn",
    firstName: "Jacky",
    middleInitial: "M",
    street: "168st",
    city: "Omaha",
    gender: "F",
  },
  {
    lastName: "Rand",
    firstName: "Pam",
    middleInitial: "R",
    street: "13st",
    city: "Omaha",
    gender: "F",
  },
  {
    lastName: "Schreck",
    firstName: "Ann",
    middleInitial: "P",
    street: "214st",
    city: "Elkhorn",
    gender: "F",
  },
  {
    lastName: "Simon",
    firstName: "Eric",
    middleInitial: "K",
    street: "77th",
    city: "Lincoln",
    gender: "M",
  },
  {
    lastName: "Smith",
    firstName: "John",
    middleInitial: "A",
    street: "8th",
    city: "C.Bluffs",
    gender: "M",
  },
  {
    lastName: "Thomson",
    firstName: "Ron",
    middleInitial: "F",
    street: "Farnam",
    city: "Omaha",
    gender: "M",
  },
  {
    lastName: "Young",
    firstName: "Don",
    middleInitial: "R",
    street: "Dodge",
    city: "Omaha",
    gender: "M",
  },
  {
    lastName: "Wong",
    firstName: "Carole",
    middleInitial: "S",
    street: "Broadway",
    city: "C.Bluffs",
    gender: "F",
  },
];

export const worksInput = [
  {
    lastName: "Anderson",
    firstName: "Susan",
    middleInitial: "L",
    companyName: "Mutual of Omaha",
    salary: 48000,
  },
  {
    lastName: "Brady",
    firstName: "Dan",
    middleInitial: "L",
    companyName: "FDR",
    salary: 42000,
  },
  {
    lastName: "Chen",
    firstName: "Peter",
    middleInitial: "K",
    companyName: "FDR",
    salary: 53000,
  },
  {
    lastName: "Clemson",
    firstName: "Ann",
    middleInitial: "M",
    companyName: "First Bank",
    salary: 39000,
  },
  {
    lastName: "Dale",
    firstName: "Mary",
    middleInitial: "K",
    companyName: "Mutual of Omaha",
    salary: 58000,
  },
  {
    lastName: "Gill",
    firstName: "Mary",
    middleInitial: "L",
    companyName: "Union Pacific",
    salary: 48700,
  },
  {
    lastName: "Harrison",
    firstName: "Susan",
    middleInitial: "M",
    companyName: "Union Pacific",
    salary: 54320,
  },
  {
    lastName: "Jackson",
    firstName: "Kim",
    middleInitial: "A",
    companyName: "FDR",
    salary: 68000,
  },
  {
    lastName: "Jason",
    firstName: "Pat",
    middleInitial: "M",
    companyName: "FDR",
    salary: 83000,
  },
  {
    lastName: "Kumar",
    firstName: "Paul",
    middleInitial: "T",
    companyName: "FDR",
    salary: 44000,
  },
  {
    lastName: "Orr",
    firstName: "Susanne",
    middleInitial: "S",
    companyName: "Lincoln Star",
    salary: 32000,
  },
  {
    lastName: "Peterson",
    firstName: "Mike",
    middleInitial: "E",
    companyName: "First Bank",
    salary: 37000,
  },
  {
    lastName: "Powell",
    firstName: "Tom",
    middleInitial: "E",
    companyName: "First Bank",
    salary: 54000,
  },
  {
    lastName: "Quinn",
    firstName: "Jacky",
    middleInitial: "M",
    companyName: "First Bank",
    salary: 85000,
  },
  {
    lastName: "Rand",
    firstName: "Pam",
    middleInitial: "R",
    companyName: "FDR",
    salary: 37000,
  },
  {
    lastName: "Schreck",
    firstName: "Ann",
    middleInitial: "P",
    companyName: "First Bank",
    salary: 36000,
  },
  {
    lastName: "Simon",
    firstName: "Eric",
    middleInitial: "K",
    companyName: "Mutual of Omaha",
    salary: 45000,
  },
  {
    lastName: "Smith",
    firstName: "John",
    middleInitial: "A",
    companyName: "FDR",
    salary: 55000,
  },
  {
    lastName: "Thomson",
    firstName: "Ron",
    middleInitial: "F",
    companyName: "First Bank",
    salary: 39000,
  },
  {
    lastName: "Young",
    firstName: "Don",
    middleInitial: "R",
    companyName: "Mutual of Omaha",
    salary: 27000,
  },
  {
    lastName: "Wong",
    firstName: "Carole",
    middleInitial: "S",
    companyName: "First Bank",
    salary: 44000,
  },
];

export const companyInput = [
  { companyName: "First Bank", city: "Omaha" },
  { companyName: "FDR", city: "Omaha" },
  { companyName: "Lincoln Star", city: "Lincoln" },
  { companyName: "Mutual of Omaha", city: "Omaha" },
  { companyName: "Union Pacific", city: "Omaha" },
];
